# Generated by Django 3.0.8 on 2020-08-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='step_number',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='website',
        ),
        migrations.AddField(
            model_name='instruction',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_status_new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.Source')),
                ('title', models.CharField(max_length=200)),
                ('page_number', models.IntegerField()),
            ],
            bases=('recipes.source',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.Source')),
                ('recipe_url', models.URLField()),
            ],
            bases=('recipes.source',),
        ),
        migrations.AddField(
            model_name='source',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
