# Generated by Django 3.0.8 on 2020-08-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200802_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='recipe_url',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
